language: python
python:
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "pypy3.5"

install:
    - pip install .

script:
    - pytest

deploy:
    provider: pypi
    user: "pfrommerd"
    password: "mnpwifeo"
    distributions: "sdist bdist_wheel"
    on:
        branch: experimental
